### ISSUE TITLE
get_clean_factor_and_forward_returns crashes when there is only one ticker

### ISSUE THREAD

**Issue by victormartingarcia** [quantopian/alphalens#135]
Seems that `alphalens.utils.get_clean_factor_and_forward_returns` crashes when there is only one ticker:

> ValueError: Bin edges must be unique: array([-0.01466337, -0.01466337, -0.01466337, -0.01466337, -0.01466337, -0.01466337])

It can be easily reproduced with the example notebook [tear_sheet_walk_through.ipynb](https://github.com/quantopian/alphalens/blob/master/alphalens/examples/tear_sheet_walk_through.ipynb) , instantiating ticker_sector dictionary with just one ticker:

`ticker_sector = {'A': 4}`

**Comment by luca-s** [comment]
You could try decreasing the number of quantiles or to use the "bin" option (and to set "quantiles=None"). For details see [here](https://github.com/quantopian/alphalens/issues/105).

Another workaround would be to rank the factor and pass that to alphalens ( factor.rank(method='first') ) instead of the plain factor.

The best solution depends on your data and how you want to perform the data quantization. Please let me know if this helps.

**Comment by luca-s** [comment]
Just to add some more information, if you set ` ticker_sector = {'A': 4}` and `quantiles=5` the code tries to create 5 quantiles out of a group made of one single element, that is the reason why it crashes.

**Comment by luca-s** [comment]
After few tests I discovered two pandas bugs that prevent you from running successfully alphalens.utils.get_clean_factor_and_forward_returns even when you correctly set quantile=1 or bins=1:

1 - if you set quantiles=1 then pandas.qcut raises `ValueError: Bin edges must be unique`. In my opinion 1 quantile and 1 value is fine and that shouldn't raise an exception and I believe this is a special case that the [code doesn't cover](https://github.com/pandas-dev/pandas/blob/master/pandas/tools/tile.py#L209).

2 - if you set bins=1 and quantiles=None it works most of the times except when the factor values is 0. In that case a `ValueError: Bin edges must be unique` is raised. This is a [bug too](https://github.com/pandas-dev/pandas/blob/master/pandas/tools/tile.py#L107) in my opinion.

Anyway, even if I'll submit a patch to pandas you won't see those fixes soon. So I was wondering if you really need to run alphalens on a single ticker (I don't actually see the usefulness) or if you were just letting us know about this issue.

Thanks.

**Comment by victormartingarcia** [comment]
Thanks for the explanation.

Yes, I am interested in running alphalens on a single ticker. 

Let's say I have coded an algorithm that trades on a particular instrument, for example Mini S&P 500 future. It'd be awesome if I could feed the entry trades as predictive factors, and let Alphalens do its magic and tell me if there's any real alpha there.

In this scenario, running Alphalens on a single ticker seems totally valid to me

Pardon me if I'm missing something ;)

**Comment by luca-s** [comment]
Actually I thought about the scenario you described some time ago and I was planning to examine plot by plot and see if they make sense in a single ticker case. I ended up not finishing that code check because I decided that a classic even study approach would have better suited that scenario. This might be the right time to do it and actually you can already try it setting `bins=1, quantiles=None` and making sure the  factor values are not 0.

**Comment by victormartingarcia** [comment]
I've tried with `bins=1, quantiles=None` and factor values != 0. Apparently factor data computing works great:

![captura de pantalla 2017-02-17 a las 11 46 48](https://cloud.githubusercontent.com/assets/659832/23062705/2cc3f206-f507-11e6-8d54-b56fba189e23.png)

But information sheet does not work:

![captura de pantalla 2017-02-17 a las 11 47 36](https://cloud.githubusercontent.com/assets/659832/23062740/4891c21a-f507-11e6-99c2-e2e0e1bd9f02.png)

![captura de pantalla 2017-02-17 a las 11 47 56](https://cloud.githubusercontent.com/assets/659832/23062741/4b09d492-f507-11e6-861e-e4ec8990809e.png)

**Comment by victormartingarcia** [comment]
Great, it works this way

Thank you so much for your help
