### ISSUE TITLE
Better error message for not enough quantiles for factor values

### ISSUE THREAD

**Issue by CaptainKanuk** [quantopian/alphalens#152]
Factors which draw from small discrete sets (such as a buy/sell factor with -1, 0, 1) fail in alphalens. A fairly uninformative error is generated. For repro you can try running it on a factor constructed from this sentiment data. We should have a more elegant failure or some kwarg to tell alphalens the factor is discrete. I solved the issue locally by adding in a tiny amount of random noise to my factor, effectively making it continuous.

https://www.quantopian.com/data/sentdex/sentiment

**Comment by luca-s** [comment]
For factors containing discrete values you can use the 'bins' argument that force alphalens to perform a binning on the values instead of creating quantiles. With discrete values from your example (-1,0,1) you could try something like:

```
bins=[-1.5, -0.5, 0.5, 1.5] 
quantiles=None 
```
For details see [here](https://github.com/quantopian/alphalens/issues/105)

Regarding a more informative error,I agree with you.

**Comment by CaptainKanuk** [comment]
Got it, thanks. This is helpful and having a more useful error, or a kwarg for discrete data, would be awesome.

**Comment by mmargenot** [comment]
I have run into this same issue before with continuous factors that simply have a lot of 0 values. I have solved this similarly to Delaney, by adding a very small amount of random noise. In this case, I don't think specifying the bins will solve the issue since I do not know the quantiles.

**Comment by luca-s** [comment]
@mmargenot  I would consider your issue different from the one reported by @CaptainKanuk. The problem you faced is due to pd.qcut (the function that calculate the quantiles) not being able to provide a workaround when identical values span more than one quantile. Interesting to note, in pandas 0.20.0 they added an option (duplicates='raise'|'drop') that fixes that, which would result in less bins than specified, and some larger bins (with more elements) than others. We could make use of that option eventually.

Until then, another workaround could be to use bins=5 and quantiles=None, that chooses the bins/quantiles to be evenly spaced according to the values themselves, while quantiles=5 chooses the bins/quantiles so that you have the same number of records in each bin/quantile.

**Comment by luca-s** [comment]
Closing this
