### ISSUE TITLE
pandas_webreader can not be used

### ISSUE THREAD

**Issue by timinGo** [quantopian/alphalens#173]
I am trying to follow the experiements to study alphalens.
The problem is 

```python
import pandas_datareader.data as web
pan = web.DataReader(list(ticker_sector.keys()), "yahoo", '2014-12-01')
```
and

```python
import pandas_datareader.data as web
pan = web.DataReader(list(ticker_sector.keys()), "google", '2014-12-01')
```

always can not be used,
is that possible to given a data file directly?

Thanks a lot!

**Comment by femtotrader** [comment]
`DataReader` is deprecated in Pandas since Pandas 0.19
see https://github.com/pandas-dev/pandas/blob/master/pandas/io/data.py
http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#whatsnew-0190-prior-deprecations

this is a standalone project available at https://github.com/pydata/pandas-datareader

You might install latest version from source (not from pip)

**Comment by twiecki** [comment]
@femtotrader I think that's what he's already using.

@timinGo What's the error? You should be able to just feed in your own data.

**Comment by timinGo** [comment]
@twiecki 
@femtotrader 
yep, I am trying to fellow the instruction as:
```Python
import pandas_datareader.data as web
pan = web.DataReader(list(ticker_sector.keys()), "google", '2014-12-01')
```

As I am trying to understand and modify some parts of codes, it is might be useful for me to get views from data structure.
Wow, now the problem is I can not use the example data, is that possible someone can give some data exactly equal to the data given in code_example.

**Comment by MichaelJMath** [comment]
@timinGo , Are you transposing the panel after reading the data from Google? 
``` python
import pandas_datareader.data as web
pan = web.DataReader(ticker_sector.keys(), "yahoo", '2014-12-01')
pan = pan.transpose(2,1,0)
```

**Comment by femtotrader** [comment]
My mistake! @twiecki I shouldn't send email during holidays before going to "playa".

But my advice to use latest development version still apply until 0.5.0 is not released see https://github.com/pydata/pandas-datareader/issues/371

About Panel, be aware of depreciation see http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#whatsnew-0200-api-breaking-deprecate-panel and https://github.com/pydata/pandas-datareader/issues/297

**Comment by timinGo** [comment]
@femtotrader 
@MichaelJMath 

I am pretty sure this trouble is absolutely not about panel and which version problem.
The panel is not able to download from yahoo or google(ps: google has been blocked in China), and yahoo seems not work.
Is that fine to give a data file in the example folder, such as open_price.csv?

**Comment by MichaelJMath** [comment]
@TiminGo, the yahoo finance API was discontinued by Yahoo. I meant to put "google" in the code snippet above. The Google API should work although I noticed there are some bad data points. That said, it should work fine for the alphalens example.

``` python
import pandas_datareader.data as web
pan = web.DataReader(ticker_sector.keys(), "google", '2014-12-01')
pan = pan.transpose(2,1,0)
pan.loc[:,:,'Open'].head()
```
This code outputs:
``` 
              AAPL   GOOGL
Date                      
2014-12-01  118.81  545.09
2014-12-02  113.50  539.45
2014-12-03  115.75  537.50
2014-12-04  115.77  537.64
2014-12-05  115.99  536.70
```

**Comment by timinGo** [comment]
@MichaelJMath 
Really thanks your kindly reply.
Ehh, my apologize with this problem is that Google has been banned by China gov....
So that is not easy for me to get data from google

**Comment by MichaelJMath** [comment]
My apologies. I didn't catch on that you are in China. Are you able to access Quandl by any chance?

**Comment by timinGo** [comment]
@MichaelJMath  I think it might be works, just now checked web browser directly access.

**Comment by luca-s** [comment]
I understand from [here](https://stackoverflow.com/questions/44087113/error-with-pulling-data-from-yahoo-finance) and [here](https://github.com/pydata/pandas-datareader/issues/315) that yahoo API endpoint has changed and a patch has been made but hasn't been merged to the master branch of pandas-datareader yet. 

So it should be just a temporarily issue. Who can use google, can use google in the meanwhile, otherwise there are proposed workarounds in the links above.

I am closing this issue soon, because this is not Alphalens related. Feel free to re-open it if you find Alphalens related issues.

**Comment by timinGo** [comment]
#luca-s
Thanks
