### ISSUE TITLE
Will alphalens support multi-factor models in the future?

### ISSUE THREAD

**Issue by huaiweicheng** [quantopian/alphalens#177]
alphalens is awesome!
I have been used alphalens to filter several effective factors from many factors in stock market for some time.
However, by the previous step I just got several effective factors independently. 
In practice, the more common scenario is to generate a multi-factor linear model and regression the multi-factor model  (for example Fama-French 3-factor model) other than single-factor models and do hypothesis testing in this multi-factor model.
Will this multi-factor model be considered into adding up to alphalens in the future?

**Comment by luca-s** [comment]
What about generating the multi factor model by yourself and submit the combined factor to Alphalens? 

I understand that it would be convenient to let Alphalens combine multiple factors (save some lines of code), but on the other hand I can imagine multiple techniques to combine factors together, so it wouldn't be obvious how to build the multi factors model from the basic factors.  

What do you think?

**Comment by luca-s** [comment]
Just to be more specific, if I had to combine some factors together I can think at least at those basic approaches:

- rank each factor and sum them together
- rank each factor and multiply them
- calculate the zscore of each factor and sum them together
- demean factor then divide by the sum of the factor absolute values, then sum all factors together

Generally speaking, you have to normalize the factors and sum them together. It takes only few lines of code anyway.

**Comment by huaiweicheng** [comment]
@luca-s 
Thanks for your careful answers.
You may misunderstand the meaning of the combination.
I do not directly combine factor together.
Here is my method:
Firstly, for example, factor X1 and factor X2 are two effective factors, which have been tested through alphalens. In alphalens, the OLS method use equationes by  Y = $alpha$ + $beta$ * X1 and  Y = $alpha$ + $beta$ * X2.

After the fist round testing for single factor independently, I want to make a multi-factor model, which is a multiple variable regression model described by Y = $alpha$ + $beta_1$ * X1 + $beta_2$ * X2.

Through this equation, we can easily demonstrate the Y(normally this variable is Return) can be explained by X1 and X2, with the params $alpha$, $beta_1$, $beta_2$ together.

The multi-factor model is not generated by mathematical computation of X1 and X2 into a new factor X12 and re-run the alphalens. but a multiple variable regression model, which is not contained in alphalens?(I am not sure alphalens could handle this scenario)

The OLS method is used here. The variable of $x$ here  is a single factor.
https://github.com/quantopian/alphalens/blob/master/alphalens/performance.py#L213





Is that clear?

**Comment by luca-s** [comment]
ah yes, I actually misunderstood your point. So, let me understand better, currently alphalens.performance.factor_alpha_beta calculates alpha and beta as you described: 
```
Y = alpha + beta * X

Y = factor returns (mean period wise return from a portfolio weighted by factor values) the dependent variable
X = market returns (period wise factor universe mean return) the independent variable
```

In your equation, `Y = $alpha$ + $beta_1$ * X1 + $beta_2$ * X2`, what are Y, X1 and X2?

**Comment by huaiweicheng** [comment]
Actually, the way we used of the regression is quite different.
In my previous experience, we use regression as follows.

For a single factor model regression, 
```
Y = alpha + beta * X
Y = An array of returns consists of all stocks (the dependent variable)
X = An array of normalized factors consists of all stocks (the independent variable1)
```

For a multi-factor model regression, 
```
Y = alpha + beta1 * X1 + beta2 * X2
Y = An array of returns consists of all stocks (the dependent variable)
X1 = An array of normalized factors (factor 1) consists of all stocks (the independent variable1)
X2 = An array of normalized factors (factor 2) consists of all stocks (the independent variable2)

```
Using the 2-factor model, we can get the knowledge of what level that factor 1 and factor 2 explain return together. The Adjust R-squared is normally higher than single-factor model(When there is no multi-collinearity we may think the model is better than a single-factor model)

You can see the way in 
[http://www.investopedia.com/terms/m/multifactor-model.asp](url)

I haven't figured out how to do this multi-factor model in the way alphalens used.
Alphalens use a regression, where dependent variable is calculated by a weighted return using a single factor. I have no idea how to handle this settings in a multi-factor scenario.

**Comment by luca-s** [comment]
I guess the term 'factor' is unfortunate in this context because it can refer to two distinct concepts:
- factor, the input of Alphalens (this is what I meant with 'factor' and what Alphalens means in its documentation)
- factor, one of the factors in a 'Multi-Factor Model' (this is what you meant with 'factor')

This explains why we have different meaning for X and Y in the equations ;)

So, after this long misunderstanding, I agree with you that it would be nice to have a  'Multi-Factor Model'  evaluation of the portfolio other than a simple one factor model, but I don't believe it's easy to do because we don't have the 'Multi-Factor Model' data. In the case of a single-factor model  (CAPM) Alphalens computes the market returns from Alphalens input factor averaging all the stocks returns. Given that the Alphalens input factor uses a big enough universe of stocks, the average returns is quite close to the actual market returns. I don't believe we can do the same for a  'Multi-Factor Model'. For example in the case of Fama–French three-factor model we don't have the SMB and HML data.

@twiecki  How does pyfolio compute Fama–French exposure? Is that possible to borrow some ideas from there?

**Comment by huaiweicheng** [comment]
More specifically, 
We assume a scenario, that the stock return can be explained by ev(enterprise value) and ni(net income).
So for every stock, the return of stock i 
```
R_i = alpha + beta1 * ev_i + beta2 * ni_i
```
Using all the R_i ev_i and ni_i of all stocks we get a alpha , beta1 and beta2  in the regression model.
If we can get a regression model like this, we can get the conclusion that Return is determined by ev and ni.
So in the stock market we can get the alpha of stock_i between R_i(calculated from ev and ni in the regression equation) and R_i(actual) .

The factor in my context denotes a feature data that each stock has. such as ni, ev, P/E ratio and so on.

**Comment by luca-s** [comment]
Sure, it makes sense. My only concern is that we don't have ev_i nor ni_i and it's not obvious how to get them

**Comment by twiecki** [comment]
We've actually been working on a multi-factor risk model. So this is definitely something we want to support in alphalens. Any help would be much appreciated.

**Comment by jameschristopher** [comment]
Just to add my two cents here, I think we are already pursuing this function - but we just stopped at the risk model @luca-s described above. From an engineering and interface standpoint it would be best to start with generalizing the functions that use the baked in risk model to instead accept any linear model and associated data, the former being easier to implement than the later. This issue is definitely in scope, we are just currently implementing a naive version of it.

**Comment by huaiweicheng** [comment]
@luca-s  Yes. That is also my concern. I have no idea how to do such multi-factor regression in current version of alphalens.

@twiecki  Wonderful to hear that and would like to contribute in this feature. Any ideas or codes could share at the current time?  Can't wait to see any new progresses of alphalens.

**Comment by jameschristopher** [comment]
Related https://github.com/quantopian/alphalens/issues/180

**Comment by georgh0021** [comment]
Hello all, Q has recently done a lot of work on multi-factor risk models, and we are definitely looking to support this kind of functionality in both pyfolio and alphalens. As mentioned, #180 will be a step in the right direction. I've worked very closely with the risk model work on pyfolio, so I'll do the same for alphalens. Of course, any suggestions/recommendations are welcome!

After alpha decomposition is delivered, I'll move on to generalizing the functions so that alphalens as a whole supports multi-factor models. As @jameschristopher pointed out, this should not be very difficult.

@twiecki @luca-s does that sound like a plan?

**Comment by luca-s** [comment]
As this issue is just a question and development is discussed in #180, I am closing this. Feel free to reopen this if required

**Comment by eigenfoo** [comment]
@luca-s unfortunately I'm no longer available to finish up #180. It is currently sitting on my fork of alphalens: anyone should feel free to pick up the work!

**Comment by luca-s** [comment]
@eigenfoo  Would you like to comment on PR #185 and state what's missing to complete the PR?

**Comment by lefig** [comment]
I was wondering... whether there has been any updates on this (concerning multi-factor support). Thanks

**Comment by twiecki** [comment]
@lefig What specifically would you like to have? The only thing I can think of are correlations in terms of additional analyses.
