### ISSUE TITLE
why is the plot 'cumulative return by quantile' has ylabel as 'Log Cumulative Return'

### ISSUE THREAD

**Issue by evril7490** [quantopian/alphalens#194]
In plotting.py, func plot_cumulative_returns_by_quantile(quantile_returns, period=1, ax=None), the ylabel is 'Log Cumulative Return', may I know where does the 'Log' come from?

**Comment by luca-s** [comment]
From [here](https://github.com/quantopian/alphalens/blob/477f617bbc71abfd373b1c49b53a58494a009a24/alphalens/plotting.py#L806): ` yscale='symlog'`

**Comment by evril7490** [comment]
Oh, thanks, totally missed that. And I assumed the reason for log scale the return is to be able to compare the different quantile cumulative returns.

**Comment by luca-s** [comment]
I wasn't the one that made that choice but I agree with you that comparing different quantiles could be a reason for that. Also it is convenient to plot cumulative returns in log scale because a vertical move of 0.01 corresponds to a 1% change at any point in the figure. So it is easier to compare performance across  the whole time frame of the plot.
