### ISSUE TITLE
The behavior of get_clean_factor_and_forward_returns in regards to periods is strange.

### ISSUE THREAD

**Issue by mmargenot** [quantopian/alphalens#292]
If I say I want `(1, 15, 30)` as periods, I occasionally get formatted outputs like:
<img width="945" alt="image" src="https://user-images.githubusercontent.com/15113371/38898805-16d23556-4264-11e8-8daa-c4eb3b47041c.png">

There does not seem to be a firm way to predict whether my period value will be augmented by 1, 2, or more. To have a non-deterministic change like this seems undesirable. Is this expected behavior?

**Comment by luca-s** [comment]
The days we expect to see reported by Alphalens are trading days but it can be tricky to detect the actual number of trading days since there is no trading calendar passed to Alphalens. There is a logic though that tries to infer the trading calendar and so the actual trading days. This logic probably fails with some input. If there is a way I can replicate the bug I will fix that.

**Comment by luca-s** [comment]
Just an update. I found out that the issue since Alphalens is not aware of the public holidays the computation of the periods goes wrong. For short periods we don't see the problem because Alphalens performs several tests and it is unlikely that in all those tests there is always  a public holiday in between the period. The longer the period the more likely Alphalens fails in detecting the right period length. I will find a solution.

**Comment by mmargenot** [comment]
Nice catch! It definitely seems worse as periods get longer.

**Comment by luca-s** [comment]
Fixed in  #295
