### ISSUE TITLE
performance.py error when weights freq is None

### ISSUE THREAD

**Issue by tradeasystems** [quantopian/alphalens#316]
On line 205 , method to_weights .

the expression 

`weights.index.levels[0].freq = factor_data.index.levels[0].freq` 

is trying to assign a freq , but when is None, raise an error

same as [here](https://stackoverflow.com/questions/46217529/pandas-datetimeindex-frequency-is-none-and-cant-be-set) 

I think could be fixed just with that 

`weights.index.levels[0].freq= pd.tseries.frequencies.to_offset(factor_data.index.levels[0].freq)`

**Comment by luca-s** [comment]
The 'factor_data'  should conform to the output of [utils.get_clean_factor_and_forward_returns](https://github.com/quantopian/alphalens/blob/master/alphalens/utils.py) and there documented. it requires `freq` to be set. So I don't know why you encountered that error. Could you please share some code that produces that error so that we can better understand the issue?

**Comment by luca-s** [comment]
There is a function, [infer_trading_calendar](https://github.com/quantopian/alphalens/blob/master/alphalens/utils.py#L172), which can be used to computed `freq` but that doesn't solve the issue: why isn't `freq` set in your code?

**Comment by luca-s** [comment]
Feel free to reopen this issue if you have a test case where Alphalens fails
