### ISSUE TITLE
Newbie issues: "ModuleNotFoundError: No module named 'alphalens'"

### ISSUE THREAD

**Issue by udayb** [quantopian/alphalens#321]
I just installed alphalens using pip and installed Jupyter as suggested.
On executing daily_factor_synthetic_data.ipynb from examples in the Jupyter , I get the following error
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-c6c521c0774b> in <module>()
      5 import matplotlib.pyplot as plt
      6 
----> 7 from alphalens.tears import (create_returns_tear_sheet,
      8                       create_information_tear_sheet,
      9                       create_turnover_tear_sheet,

ModuleNotFoundError: No module named 'alphalens'

Please let me know if there is an alias where I can I ask dumber questions.

Thanks
Uday

**Comment by luca-s** [comment]
So, if you simply  import alphalens in a Notebook, does it work or do you get an error?

**Comment by udayb** [comment]
[image: image.png]

I am very new to Jupyter and Python. So please excuse the mistakes.

Thanks
Uday

**Comment by luca-s** [comment]
@udayb the image was not uploaded

**Comment by udayb** [comment]
> 
> 
> @udayb the image was not uploaded

It shows that alphalens is not found. Others seem to work fine.
I had installed it via pip as suggested and assumed that the path would be updated implicitly. Let me know if I am missing something. I am new to Python.

![2018-10-12](https://user-images.githubusercontent.com/6234091/46901107-efff4600-ceca-11e8-8ad6-092b2655f716.png)

Thanks
Uday

**Comment by luca-s** [comment]
Thanks, I can see the image now. It seems that Jupyter NB is using python3. Did you pip-install Alphalens for python2 or python3?

**Comment by udayb** [comment]
I did the following
 sudo apt install python-pip
and
 pip install alphalens

I did not choose anything specifically wrt python itself.

Thanks
Uday

**Comment by luca-s** [comment]
try tunning:

`pip3 install alphalens`

**Comment by udayb** [comment]
Still the same issue. This is on ubuntu 18.04 would that matter?

Thanks
Uday

**Comment by luca-s** [comment]
I am sorry that I was not able to help you but this issue is not really Alphalens related, this has to do with you system and it is very hard for me to debug the problem without having access to your machine. I would suggest to read your distribution documentation on how to install python modules. 

On my machine, which is an OS similar to your ubuntu 18.04  I simply run pip (or pip3) install with the `--user` option (so that the package is installed in my home folder). The python environment variables already include my home as search path for python modules, so the installed modules work right away. 

In your case I would double check that Alphales in actually installed in the system (check the files are there) and then I would make sure that python module search path includes the folder where Alphalens is actually installed.

**Comment by udayb** [comment]
No worries. I'll figure it out.

Is there an alias for this effort that I can join. Raising issues for
teething problems like mine is not fair for you developers.

Thanks
Uday

**Comment by davidmcomfort** [comment]
I used conda to install alphalens `conda install -c conda-forge alphalens` and that solved the issue. It installs version `0.3.6.`
