### ISSUE TITLE
ValueError: freq must be Day, BDay or CustomBusinessDay

### ISSUE THREAD

**Issue by holymonkey808** [quantopian/alphalens#351]
## Problem Description
Having the above error when providing a multiindex dataframe without setting freq. Anyway to set date freq after dataframe is created? 
should Performance.py line 740 and 793 be changed to use pd.infer_freq?

**Please provide a minimal, self-contained, and reproducible example:**
```python
[Paste code here]
```

**Please provide the full traceback:**
```python
[Paste traceback here]
```

**Please provide any additional information below:**

## Versions

* Alphalens version: 0.3.6
* Python version: 3.5.6
* Pandas version: 0.22
* Matplotlib version: 3.0.0

**Comment by luca-s** [comment]
This happened because the input dataframe was not generated by [alphalens.utils.get_clean_factor_and_forward_returns](https://github.com/quantopian/alphalens/blob/master/alphalens/utils.py#L632), which is fine as long as you read the function documentation and makes sure your input dataframe is built in the same way as `get_clean_factor_and_forward_returns` does. It would also help to have a look at the function implementation, which would clarify few details.
