### ISSUE TITLE
Add CONTRIBUTORS file

### ISSUE THREAD

**Issue by twiecki** [quantopian/alphalens#78]
To highlight contributions and give credit where it is due.

**Comment by jameschristopher** [comment]
shouldn't this be taken care of here?

https://github.com/quantopian/alphalens/graphs/contributors

**Comment by twiecki** [comment]
good point, yeah. we should just link to that in the readme.

**Comment by jameschristopher** [comment]
though it looks like Luca's contribution isn't showing up. is there like a minimum?

**Comment by jameschristopher** [comment]
added to README here https://github.com/quantopian/alphalens/commit/9ef467af5fd28082293f3c85a7c370cd1c64e98d

**Comment by jameschristopher** [comment]
https://github.com/luca-s you should make sure that you have yor email on your local machine github setup so that you get credit when your contributions are merged
![screen shot 2016-08-29 at 11 17 44 am](https://cloud.githubusercontent.com/assets/13838056/18056655/cda3048c-6dda-11e6-8835-144d98541d41.png)
