### ISSUE TITLE
Create fake factor that's very predictive

### ISSUE THREAD

**Issue by twiecki** [quantopian/alphalens#80]
For demonstrating the capabilities and what it would like if a factor was predictive, we should include made-up data of such a factor with look-ahead bias.

**Comment by luca-s** [comment]
It should be straightforward to modify alphalens/examples/tear_sheet_walk_through.ipynb so that the factor looks at future prices instead of past ones (one line of code change). Alternatively, you could keep the current factor but shift it back in time so that everyday you know the factor of tomorrow. Currently the factor is shifted forward one day to avoid Look-Ahead bias, but we want to introduce the bias to have a predictive factor, so we do the opposite (still one line of code change).

**Comment by twiecki** [comment]
yep, that would be a good way to do it. want to do a PR?

**Comment by luca-s** [comment]
No really, I was just suggesting that because I use the trick to do my own testing sometime.

**Comment by twiecki** [comment]
Fair enough, thanks for the suggestion!

**Comment by jameschristopher** [comment]
fixed https://github.com/quantopian/alphalens/pull/121
